### ISSUE TITLE
"Cookie nonce is invalid" error from Login Mutation

### ISSUE THREAD

**Issue by jbloth** [wp-graphql/wp-graphql-jwt-authentication#94]
Hi, I am using the login mutation in GraphiQL like this:

```mutation LoginUser($input: LoginInput!) {
  login(input: $input) {
    authToken
    user {
      id
      name
      userId
      nicename
    }
    customer {
      customerId
      id
      firstName
    }
  }
}
```
I can only log in the admin. With every other user, I get the following error:

```
{
  "errors": [
    {
      "debugMessage": "Cookie nonce is invalid",
      "message": "Internal server error",
      "category": "internal"
    }
  ]
}
```

Help yould be greatly appreciated. Thanks for the great work!

**Comment by HiepVu511** [comment]
+1. I'm facing this issue too.

**Comment by kidunot89** [comment]
@jbloth @HiepVu511 Doing a hard refresh on WPGraphiQL should resolve this issue.

This is caused when an the user cookie that WPGraphiQL is using is invalidated outside of WPGraphiQL by a request from an external app or tool made on the same machine

**Comment by joshuaiz** [comment]
Facing this issue as well.

@kidunot89 what do you mean by 'hard refresh'? I tried logging out completely, logging in again and reloading - still getting this issue.

**Comment by joshuaiz** [comment]
Update: after trying a few things, if you try to log in from WPGraphiQL with a different user than the one you are currently logged in as, the mutation will fail. This makes sense as you are already logged in so you can't log in again in the same browser.

**Comment by NeniEmSu** [comment]
> Update: after trying a few things, if you try to log in from WPGraphiQL with a different user than the one you are currently logged in as, the mutation will fail. This makes sense as you are already logged in so you can't log in again in the same browser.

This is the answer actually, 

Is there a reason the issue is still open?

**Comment by Najamuddin1** [comment]
`{
  "errors": [
    {
      "debugMessage": "Cookie nonce is invalid",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "trace": [
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-content\\plugins\\wp-graphql\\src\\Request.php",
          "line": 405,
          "call": "WPGraphQL\\Request::has_authentication_errors()"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-content\\plugins\\wp-graphql\\src\\Request.php",
          "line": 668,
          "call": "WPGraphQL\\Request::after_execute(instance of GraphQL\\Executor\\ExecutionResult)"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-content\\plugins\\wp-graphql\\src\\Router.php",
          "line": 468,
          "call": "WPGraphQL\\Request::execute_http()"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-content\\plugins\\wp-graphql\\src\\Router.php",
          "line": 270,
          "call": "WPGraphQL\\Router::process_http_request()"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-includes\\class-wp-hook.php",
          "line": 303,
          "call": "WPGraphQL\\Router::resolve_http_request(instance of WP)"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-includes\\class-wp-hook.php",
          "line": 327,
          "call": "WP_Hook::apply_filters(null, array(1))"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-includes\\plugin.php",
          "line": 518,
          "call": "WP_Hook::do_action(array(1))"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-includes\\class-wp.php",
          "line": 388,
          "function": "do_action_ref_array('parse_request', array(1))"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-includes\\class-wp.php",
          "line": 750,
          "call": "WP::parse_request((empty string))"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-includes\\functions.php",
          "line": 1291,
          "call": "WP::main((empty string))"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\wp-blog-header.php",
          "line": 16,
          "function": "wp()"
        },
        {
          "file": "C:\\xampp\\htdocs\\woo-graph\\index.php",
          "line": 17,
          "function": "require('C:\\xampp\\htdocs\\woo-graph\\wp-blog-header.php')"
        }
      ]
    }
  ]
}

`

Im Using CHECKOUT_MUTATION in wp-graphql-woocommerce an getting this Error

**Comment by oseisaac** [comment]
> `{ "errors": [ { "debugMessage": "Cookie nonce is invalid", "message": "Internal server error", "extensions": { "category": "internal" }, "trace": [ { "file": "C:\xampp\htdocs\woo-graph\wp-content\plugins\wp-graphql\src\Request.php", "line": 405, "call": "WPGraphQL\Request::has_authentication_errors()" }, { "file": "C:\xampp\htdocs\woo-graph\wp-content\plugins\wp-graphql\src\Request.php", "line": 668, "call": "WPGraphQL\Request::after_execute(instance of GraphQL\Executor\ExecutionResult)" }, { "file": "C:\xampp\htdocs\woo-graph\wp-content\plugins\wp-graphql\src\Router.php", "line": 468, "call": "WPGraphQL\Request::execute_http()" }, { "file": "C:\xampp\htdocs\woo-graph\wp-content\plugins\wp-graphql\src\Router.php", "line": 270, "call": "WPGraphQL\Router::process_http_request()" }, { "file": "C:\xampp\htdocs\woo-graph\wp-includes\class-wp-hook.php", "line": 303, "call": "WPGraphQL\Router::resolve_http_request(instance of WP)" }, { "file": "C:\xampp\htdocs\woo-graph\wp-includes\class-wp-hook.php", "line": 327, "call": "WP_Hook::apply_filters(null, array(1))" }, { "file": "C:\xampp\htdocs\woo-graph\wp-includes\plugin.php", "line": 518, "call": "WP_Hook::do_action(array(1))" }, { "file": "C:\xampp\htdocs\woo-graph\wp-includes\class-wp.php", "line": 388, "function": "do_action_ref_array('parse_request', array(1))" }, { "file": "C:\xampp\htdocs\woo-graph\wp-includes\class-wp.php", "line": 750, "call": "WP::parse_request((empty string))" }, { "file": "C:\xampp\htdocs\woo-graph\wp-includes\functions.php", "line": 1291, "call": "WP::main((empty string))" }, { "file": "C:\xampp\htdocs\woo-graph\wp-blog-header.php", "line": 16, "function": "wp()" }, { "file": "C:\xampp\htdocs\woo-graph\index.php", "line": 17, "function": "require('C:\xampp\htdocs\woo-graph\wp-blog-header.php')" } ] } ] }
> 
> `
> 
> Im Using CHECKOUT_MUTATION in wp-graphql-woocommerce an getting this Error

Did you find a solution to this ?
